### PR TITLE
update lock file -> update psqlgraph -> remove py2neo

### PR DESCRIPTION
**Pull request by paulineribeyre**
this is blocking unit tests in dictionary repos

### Bug Fixes
- Update lock file -> update psqlgraph -> remove broken py2neo dependency

### CODE REVIEW

**Review by mfshao — APPROVED** [review]
👍

**Review by themarcelor — APPROVED** [review]
+1
I don't see the actual pyproject.toml change but maybe the fix has been seamlessly absorbed by `poetry update` (right?)

**Review by williamhaley — APPROVED** [review]
lgtm! 👍

**Comment by paulineribeyre** [comment]
@themarcelor i just ran `poetry update` to update the lock file, no poetry dependency change was needed

**Pull request merged**
